MVR4
I(evoluta:6"6;%#dfG%$ddfG%$solG%#exG%#eyG%&tsumaG%)tevolutaG%%funcG%&paramG%"iG
%)intervalG%*intervalpG%&sing1G%&sing2G%&sola1G%&sola2G%%tempG%"KG%%solaG%%solx
G%#jaG%#jxG%&solx1G%&solx2G%&temp1G6#%UCopyright~2004~by~Gabriel~Dimitriu~Spiru
~Haret~gr~21GF$C0@$/9#""%C%>8+&9"6#""">8,&FJ6#""#>8.;-%&evalfG6#&FJ6#""$-FV6#&F
J6#FE@$/FD""!C)-%&printG6#%ipprocedura~pentru~calculul~si~plotarea~evolutei~rea
lizata~de~Dimitriu~Gabriel~gr~21~Spiru~HaretG-F^o6#%LApelul~functiei~:~evoluta(
func,param,Ix,Iy)G-F^o6#%%undeG-F^o6#%Rfunc~este~curba~pe~caruia~vrem~sa-i~face
m~evolutaG-F^o6#%Fparam~este~numele~parametrului~curbeiG-F^o6#%VIx,Iy~este~inte
rvalul~pe~care~dorim~sa~facem~plotareaG-%'RETURNGF$>8$-%%diffG6$FHFN@%3/-%%type
G6$&FcpFK%(numericG%&falseG/-F[q6$&FcpFPF^qF_qC%>89F[o?(8--%$minG6#-%"$G6#FSFL-
%$maxGF[r%%trueGC%>84-%'fsolveG6%F]qFN;Fhq,&FhqFLFLFL>8<-Ffr6%FcqFNFhr@$30Fdr%%
NULLG0F[sFas@$33/-F[q6$Fdr%)functionGF_q/-F[q6$F[sFisF_q/F[sFdrC$>&876#FfqFdr>F
fq,&FfqFLFLFL>Ffq,&FfqFL!""FL>FfqFgt>8%-Fep6$FcpFN-%%withG6#%'linalgG>%%KnumG-%
%normG6$FcpFQ>%)tnumitorG-%$detG6#-%(convertG6$7$FcpFjt%'matrixG>85*&FguFLFbu!"
$>Fav-%)simplifyG6#Fav-F^o6#/.FavFav@%/-F[q6$FguF^qF_qC%>88F[o?(FhqFiqFLF_rFarC
$>Fdr-Ffr6%FguFNFhr@$F`s@$FfsC$>&866#FbwFdr>Fbw,&FbwFLFLFL>Fbw,&FbwFLFgtFL>FbwF
gt@%43/FguF[o/F^wFarC5>8),&*$F]qFQFL*$FcqFQFL>8**&F[yFLFguFgt>F`y-Ffv6#F`y>8',&
&FHFKFL*&FcqFLF`yFLFgt>8(,&&FHFPFL*&F]qFLF`yFLFL>Ffy-Ffv6#Ffy>F[z-Ffv6#F[z-F^o6
#%UCoordonatele~parametrice~ale~cercului~osculator~suntG-F^o6$FfyF[z>80-%(unapp
lyG6$FfyFN>81-F][l6$F[zFN-F^u6#%&plotsG-%+setoptionsG6#/%%axesG%&boxedG>%#p1G-%
%plotG6%7%FhyF]z/FNFS/%&colorG%$redG/%&titleG%(functiaG>%#p2G-F_\l6%7%FfyF[zFb\
l/Fd\l%%blueG/Fg\lF"-F^o6#%\oCu~albastru~este~plotata~evoluta~iar~cu~rosu~este~
plotata~functiaG@$1F[oFbwC&-F^o6'%FCurbura~este~diferita~de~zero~pentru~GFN%,di
ferit~de~GF`x%(~puncteG?(FhqF[oFLFbwFar>&826#Fhq7$-F[[l6#&F]xF`^l-F`[lFc^l>83-F
\v6$F_^l%%listG>%#p3G-F_\l6&Fg^l/%&styleG%&pointG/%'symbolG%'circleG/Fd\l%&blac
kG@$1F[oFfqC&-F^o6%%joSe~scot~din~domeniul~de~definitie~locurile~unde~se~anulea
za~derivata~1~si~anumeGFdt%'puncteG?(FhqF[oFLFfqFar>&8:F`^l7$-F[[l6#&FatF`^l-F`
[lFd`l>8;-F\v6$Fa`lFj^l>%#p4G-F_\l6&Fh`lF__lFb_lFe_l@%3Fe]lFh_l>%#p5G-%(display
G6$<&F\alF]\lF\_lFj\l/Fg\l%6functia~si~evoluta~saG@%Fe]l>Fbal-Fdal6$<%F]\lF\_lF
j\lFgal@%Fh_l>Fbal-Fdal6$<%F\alF]\lFj\lFgal>Fbal-Fdal6$<$F]\lFj\lFgalC%-F^o6#%e
nNu~avem~evoluta~deoarece~K~este~0~in~toate~punctele~curbeiGFc[l>FbalF^\l-Fap6#
FbalF$6)F]\lFj\lF\_lF\alFbalFbuFguF$
