M7R0
I*suprafataf*6"6B%)intervalG%"iG%"jG%&paramG%%sys1G%#N1G%#N2G%#NfG%"NG%%dffxG%&
dffxfG%)repgaussG%*repgausstG%+repgausstfG%'puncteG%$pasG%%funcG%&funcfG%%valxG
%%valyG%(plotareG%/hipersuprafataG%"eG%#e1G%#e2G%#e3G%#s1G%#s2G%#s3G%#s4G%&temp
1G%"kG6#%UCopyright~2004~by~Gabriel~Dimitriu~Spiru~Haret~gr~21GF$C,-%%withG6#%'
linalgG-FJ6#%&plotsG@$/9#"")C->%$solG%%NULLG>%"gGFW>%"hGFW>%"JGFW>84&9"6#""">&8
'F\o&F[o6#""#>&F`oFbo&F[o6#""&>85-%(unapplyG6%FinF_oFeo>&8$F\o;-%&evalfG6#&F[o6
#""$-Fcp6#&F[o6#""%>&F`pFbo;-Fcp6#&F[o6#""'-Fcp6#&F[o6#""(>82-Fcp6#&F[o6#FS@$2F
RFSC,-%&printG6#%[qprocedura~pentru~calculul~si~plotarea~suprafetei~realizata~d
e~Dimitriu~Gabriel~gr~21~Spiru~HaretG-Fdr6#%QApelul~functiei~:~suprafata(func,p
aram,Ix,Iy,Nr)G-Fdr6#%%undeG-Fdr6#%Qfunc~este~curba~careia~vrem~sa-i~facem~supr
afataG-Fdr6#%Oparam~este~numele~primului~parametru~al~curbeiG-Fdr6#%Yparam~este
~numele~celui~de-al~doilea~parametru~al~curbeiG-Fdr6#%joIx,Iy~este~intervalului
~pentru~primul~parametru~pe~care~dorim~sa~facem~plotareaG-Fdr6#%joJx,Jy~este~in
tervalului~pentru~primul~parametru~pe~care~dorim~sa~facem~plotareaG-Fdr6#%[oNr~
este~numarul~de~puncte~in~care~dorim~sa~plotam~reperul~GausssG-%'RETURNGF$>&8-F
\o-%%diffG6$FinF_o>&FctFbo-Fet6$FinFeo>&8.F\o-F\p6%FbtF_oFeo>&F]uFbo-F\p6%FhtF_
oFeo>Fgn-%'matrixG6%FcoFgp7$FbtFht@%0-%%rankG6#FgnFcoOF$C@-Fdr6#%[oFunctia~data
~este~imersie~deci~este~hipersuprafata~parametrizataG>8)-%)simplifyG6#-Ffv6$-%*
crossprodG6$FbtFht/%'assumeG%%realG>8*-Ffv6#-Ffv6$-%%normG6$FdvFcoF]w>8(<%&FdvF
\o&FdvFbo&FdvFfp>8><#-%&solveG6$Fjw<$F_oFeo@$0F`xFWC(>8?-%(convertG6$F`x%%listG
>F`x-F\y6$Fjx%'vectorG>8&-%(vectdimG6#F`x>8CF]o?(8%F]oF]oFdy%%trueGC)>&Fjx6#F[z
-F\y6$F_zF^y>&&8@F`zF\o-Fcp6#&F_zF\o>&FezFbo-Fcp6#&F_zFbo>&8BF\o-%%subsG6$FdzF_
o>&Fa[lFbo-Fc[l6$F[[lFeo@$3/-%%typeG6$F`[l%'symbolGF\z/-F]\l6$Ff[lF_\lF\zC%>Ff[
l-Fc[l6$FdzFeo>F`[l-Fc[l6$F[[lF_o@$Fj[lC$>F`[lFb[l>Ff[lFg[l@$30-%)whattypeG6#F`
[l%(complexG0-Fb]l6#Ff[lFd]lC$>&8A6#Fiy7$F`[lFf[l>Fiy,&FiyF]oF]oF]o@$0FiyF]oC%>
FV-F\y6$F[^lF^y-Fdr6#%Apunctele~in~care~nu~avem~normalaG-Fdr6#FV>8,7%-Ffv6#*&F\
xF]oFaw!""-Ffv6#*&F]xF]oFawFa_l-Ffv6#*&F^xF]oFawFa_l>8+-F\p6%F\_lF_oFeo>8/7%Fbt
FhtF\_l-Fdr6#%3Reperul~gauss~esteG-Fdr6#F]`l>FY-Ffu6$FcoFco>FenFe`l?(F[zF]oF]oF
coF\z?(FdyF]oF]oFcoF\zC$>&FY6$F[zFdy-Ffv6#-Ffv6$-%(dotprodG6$&FctF`z&Fct6#FdyF]
w>&FenF]al-Ffv6#-Ffv6$-Fcal6$-Fet6$Feal&F`oFgalF\_lF]w-Fdr6#%>Prima~forma~funda
mentala~esteG-Fdr6#FY-Fdr6#%?A~doua~forma~fundamentala~esteG-Fdr6#Fen>&80F\o,&F
inF]o&F]`lF\oF]o>&F_clFbo,&FinF]o&F]`lFboF]o>&F_clFfp,&FinF]o&F]`lFfpF]o-Fdr6#-
F\y6$F_clF^y>&81F\o-F\p6%F^clF_oFeo>&F`dlFbo-F\p6%FcclF_oFeo>&F`dlFfp-F\p6%Fgcl
F_oFeo>&83F\o*&,&-%$maxG6#-%"$G6#F_pF]o-%$minGFbelFa_lF]oF[rFa_l>&F]elFbo*&,&-F
ael6#-Fdel6#F^qF]o-FgelF]flFa_lF]oF[rFa_l?(F[zF]oF]oF[rF\zC,>86-Fcp6#,&FfelF]o*
&F[zF]oF\elF]oF]o>87-Fcp6#,&F`flF]o*&F[zF]oFielF]oF]o>89-Fjo6$FdflFjfl>88-Ffu6#
7$7$F`glF`gl7$F`gl-F_dlFbgl>8;-%)surfdataG6'-F\y6$Fdgl%)listlistG/%&colorG%$red
G/%&styleG%%lineG/%*linestyleGF]o/%'labelsG7%%"xG%"yG%"zG>Fdgl-Ffu6#7$Fhgl7$F`g
l-FddlFbgl>8<-F^hl6'F`hl/Fdhl%%blueGFfhlFihlF[il>Fdgl-Ffu6#7$Fhgl7$F`gl-FhdlFbg
l>8=-F^hl6'F`hl/Fdhl%&blackGFfhlFihlF[il>&8:F`z-%(displayG6%F\hlFhilFdjl-Fdr6#%
9Imaginea~suprafetei~esteG-F][m6$-%'plot3dG6'-Fjo6$F^ilF_il/F^ilF_p/F_ilF^q/Fdh
l%&greenGF[il-F\y6$F[[mF^yF$6&FYFenFgnFVF$F$
